name: Reconcile Subscriptions

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: {}

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - name: Call reconcile endpoint
        run: |
          curl -X POST ${RECONCILE_URL:-$RECONCILE_URL} -H "Content-Type: application/json" -d '{"secret":"${{ secrets.MIGRATE_SECRET }}"}'
        env:
          RECONCILE_URL: ${{ secrets.RECONCILE_ENDPOINT }}
